# Generated by Django 5.2.8 on 2025-11-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('preferences', models.TextField()),
            ],
        ),
    ]
