# Generated by Django 5.2.8 on 2025-11-21 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.CharField(max_length=50)),
                ('reminder_message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.userprofile')),
            ],
        ),
    ]
