# Generated by Django 5.2.8 on 2025-11-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_chatbotfaq_contraceptivetype_locationinventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotfaq',
            name='answer',
            field=models.TextField(default='No answer provided'),
        ),
    ]
