# Generated by Django 5.2.8 on 2025-11-24 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_chatbotfaq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='iotreading',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.location'),
        ),
        migrations.AlterField(
            model_name='stockalert',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.location'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.location'),
        ),
        migrations.DeleteModel(
            name='LocationInventory',
        ),
    ]
